<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CHAKRI" failures="0" tests="4" name="com.app.TestNG.Extentreports.TestClass" time="0.024" errors="1" timestamp="2023-10-10T09:47:17 IST" skipped="3">
  <testcase classname="com.app.TestNG.Extentreports.TestClass" name="method1" time="0.000">
    <skipped/>
  </testcase> <!-- method1 -->
  <system-out/>
  <testcase classname="com.app.TestNG.Extentreports.TestClass" name="method2" time="0.000">
    <skipped/>
  </testcase> <!-- method2 -->
  <system-out/>
  <testcase classname="com.app.TestNG.Extentreports.TestClass" name="method3" time="0.000">
    <skipped/>
  </testcase> <!-- method3 -->
  <system-out/>
  <testcase classname="com.app.TestNG.Extentreports.TestClass" name="InitalizeExtentReport" time="0.024">
    <error message="Cannot invoke &quot;java.io.File.exists()&quot; because &quot;parentFile&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "parentFile" is null
at com.aventstack.extentreports.reporter.AbstractFileReporter.<init>(AbstractFileReporter.java:45)
at com.aventstack.extentreports.reporter.ExtentSparkReporter.<init>(ExtentSparkReporter.java:51)
at com.app.TestNG.Extentreports.BaseTest.InitalizeExtentReport(BaseTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- InitalizeExtentReport -->
  <system-out/>
</testsuite> <!-- com.app.TestNG.Extentreports.TestClass -->
